apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: keycloak-local
  title: Keycloak (Local Docker)
  description: "Keycloak Identity Provider deployed via Docker Desktop on localhost"
  tags:
    - idp
    - keycloak
  annotations:
    backstage.io/techdocs-ref: dir:.
  links:
    - url: http://localhost:8080
      title: Keycloak Local Instance
      icon: dashboard
    - url: https://www.keycloak.org/documentation
      title: Keycloak Docs
      icon: docs
spec:
  type: service
  lifecycle: development
  owner: group:default/platform-team
  system: system:default/identity
  providesApis:
    - keycloak-admin-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: keycloak-admin-api
  description: Keycloak Admin REST API
spec:
  type: openapi
  lifecycle: development
  owner: group:default/platform-team
  definition: |
    openapi: 3.0.0
    info:
      title: Keycloak Admin API
      version: "1.0.0"
    servers:
      - url: http://localhost:8080/auth
    paths:
      /admin/realms:
        get:
          summary: List realms
          responses:
            '200':
              description: OK

