apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: google-auth-local
  title: Google Auth (Local/Test)
  description: "Google OAuth 2.0 Identity Provider configured for local development or testing"
  tags:
    - idp
    - google
    - oauth
  annotations:
    backstage.io/adr-location: https://github.com/rksharma1401/storeData/tree/main/adr

  links:
    - url: http://localhost:9090/oauth2callback
      title: Google OAuth Callback Endpoint
      icon: dashboard
    - url: https://github.com/rksharma1401/storeData/tree/main/adr
      title: Architecture Decision Records
      icon: description
spec:
  type: service
  lifecycle: development
  owner: group:default/platform-team
  system: system:default/identity
  providesApis:
    - google-oauth-api
